import {
  IHealthPlan,
  IHealthPlanCategory,
  THealthFeatures,
  THealthPlanType,
} from "./health-plans.type";

export const planCategories: IHealthPlanCategory[] = [
  { id: "individual", label: "Individual Plans" },
  { id: "family", label: "Family Plans" },
  { id: "senior", label: "Senior Care" },
  { id: "corporate", label: "Corporate Plans" },
];

export const healthPlans: Record<IHealthPlanCategory["id"], IHealthPlan[]> = {
  individual: [
    {
      key: 1,
      id: "basic-individual",
      name: "Basic Care",
      price: 89,
      period: "/month",
      description: "Essential healthcare coverage for individuals",
      coverage: "80% coverage on most services",
      benefits: [
        "Regular check-ups",
        "Emergency care",
        "Prescription coverage",
        "Mental health support",
        "Digital health records",
      ],
      popular: false,
      color: "default",
    },
    {
      key: 2,
      id: "standard-individual",
      name: "Standard Care",
      price: 149,
      period: "/month",
      description: "Comprehensive coverage for your healthcare needs",
      coverage: "90% coverage on most services",
      benefits: [
        "Regular check-ups",
        "Emergency care",
        "Prescription coverage",
        "Mental health support",
        "Digital health records",
        "Specialist consultations",
        "Preventive screenings",
      ],
      popular: true,
      color: "primary",
    },
    {
      key: 3,
      id: "premium-individual",
      name: "Premium Care",
      price: 199,
      period: "/month",
      description: "Premium healthcare with additional benefits",
      coverage: "95% coverage on most services",
      benefits: [
        "Regular check-ups",
        "Emergency care",
        "Prescription coverage",
        "Mental health support",
        "Digital health records",
        "Specialist consultations",
        "Preventive screenings",
        "Wellness programs",
        "Dental coverage",
        "Vision coverage",
      ],
      popular: false,
      color: "secondary",
    },
  ],
  family: [
    {
      key: 4,
      id: "basic-family",
      name: "Family Basic",
      price: 199,
      period: "/month",
      description: "Essential healthcare coverage for families",
      coverage: "80% coverage on most services",
      benefits: [
        "Regular check-ups for all family members",
        "Emergency care",
        "Prescription coverage",
        "Mental health support",
        "Digital family health records",
        "Pediatric care",
      ],
      popular: false,
      color: "default",
    },
    {
      key: 5,
      id: "standard-family",
      name: "Family Plus",
      price: 299,
      period: "/month",
      description: "Comprehensive family healthcare coverage",
      coverage: "90% coverage on most services",
      benefits: [
        "Regular check-ups for all family members",
        "Emergency care",
        "Prescription coverage",
        "Mental health support",
        "Digital family health records",
        "Pediatric care",
        "Maternity care",
        "Specialist consultations",
        "Preventive screenings",
      ],
      popular: true,
      color: "primary",
    },
    {
      key: 6,
      id: "premium-family",
      name: "Family Premium",
      price: 399,
      period: "/month",
      description: "Premium healthcare for the whole family",
      coverage: "95% coverage on most services",
      benefits: [
        "Regular check-ups for all family members",
        "Emergency care",
        "Prescription coverage",
        "Mental health support",
        "Digital family health records",
        "Pediatric care",
        "Maternity care",
        "Specialist consultations",
        "Preventive screenings",
        "Wellness programs",
        "Dental coverage",
        "Vision coverage",
      ],
      popular: false,
      color: "secondary",
    },
  ],
  senior: [
    {
      key: 7,
      id: "senior-basic",
      name: "Senior Basic",
      price: 129,
      period: "/month",
      description: "Essential healthcare coverage for seniors",
      coverage: "85% coverage on most services",
      benefits: [
        "Regular check-ups",
        "Emergency care",
        "Prescription coverage",
        "Mental health support",
        "Digital health records",
        "Chronic condition management",
      ],
      popular: false,
      color: "default",
    },
    {
      key: 8,
      id: "senior-plus",
      name: "Senior Plus",
      price: 179,
      period: "/month",
      description: "Comprehensive healthcare for seniors",
      coverage: "90% coverage on most services",
      benefits: [
        "Regular check-ups",
        "Emergency care",
        "Prescription coverage",
        "Mental health support",
        "Digital health records",
        "Chronic condition management",
        "Home healthcare services",
        "Specialist consultations",
        "Preventive screenings",
      ],
      popular: true,
      color: "primary",
    },
    {
      key: 9,
      id: "senior-premium",
      name: "Senior Premium",
      price: 229,
      period: "/month",
      description: "Premium healthcare for seniors with full coverage",
      coverage: "95% coverage on most services",
      benefits: [
        "Regular check-ups",
        "Emergency care",
        "Prescription coverage",
        "Mental health support",
        "Digital health records",
        "Chronic condition management",
        "Home healthcare services",
        "Specialist consultations",
        "Preventive screenings",
        "Wellness programs",
        "Dental coverage",
        "Vision coverage",
        "Hearing aids",
      ],
      popular: false,
      color: "secondary",
    },
  ],
  corporate: [
    {
      key: 10,
      id: "corporate-basic",
      name: "Team Basic",
      price: 69,
      period: "/employee/month",
      description: "Essential healthcare coverage for small businesses",
      coverage: "80% coverage on most services",
      benefits: [
        "Regular check-ups",
        "Emergency care",
        "Prescription coverage",
        "Mental health support",
        "Digital health records",
        "Employee wellness portal",
      ],
      popular: false,
      color: "default",
    },
    {
      key: 11,
      id: "corporate-plus",
      name: "Team Plus",
      price: 109,
      period: "/employee/month",
      description: "Comprehensive healthcare for growing companies",
      coverage: "90% coverage on most services",
      benefits: [
        "Regular check-ups",
        "Emergency care",
        "Prescription coverage",
        "Mental health support",
        "Digital health records",
        "Employee wellness portal",
        "Specialist consultations",
        "Preventive screenings",
        "HR health dashboard",
      ],
      popular: true,
      color: "primary",
    },
    {
      key: 12,
      id: "corporate-premium",
      name: "Team Premium",
      price: 149,
      period: "/employee/month",
      description: "Premium healthcare for your entire organization",
      coverage: "95% coverage on most services",
      benefits: [
        "Regular check-ups",
        "Emergency care",
        "Prescription coverage",
        "Mental health support",
        "Digital health records",
        "Employee wellness portal",
        "Specialist consultations",
        "Preventive screenings",
        "HR health dashboard",
        "Wellness programs",
        "Dental coverage",
        "Vision coverage",
        "Family coverage options",
      ],
      popular: false,
      color: "secondary",
    },
  ],
};

//   features for comparison
export const healthComparisonFeatures: Record<
  THealthFeatures,
  Record<
    Exclude<THealthPlanType, "Family" | "Senior" | "Team">,
    string | boolean
  >
> = {
  Coverage: {
    Basic: "80% on most services",
    Standard: "90% on most services",
    Premium: "95% on most services",
  },
  "Regular Check-ups": {
    Basic: true,
    Standard: true,
    Premium: true,
  },
  "Emergency Care": {
    Basic: true,
    Standard: true,
    Premium: true,
  },
  "Prescription Coverage": {
    Basic: "Limited",
    Standard: "Standard",
    Premium: "Extensive",
  },
  "Specialist Consultations": {
    Basic: "Limited",
    Standard: "Standard",
    Premium: "Unlimited",
  },
  "Mental Health Support": {
    Basic: true,
    Standard: true,
    Premium: true,
  },
  "Preventive Screenings": {
    Basic: false,
    Standard: true,
    Premium: true,
  },
  "Wellness Programs": {
    Basic: false,
    Standard: false,
    Premium: true,
  },
  "Dental Coverage": {
    Basic: false,
    Standard: false,
    Premium: true,
  },
  "Vision Coverage": {
    Basic: false,
    Standard: false,
    Premium: true,
  },
};
